# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'knn.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 0, 921, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.FileLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.FileLayout.setContentsMargins(0, 0, 0, 0)
        self.FileLayout.setObjectName("FileLayout")
        self.cargarArchivo_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.cargarArchivo_btn.setObjectName("cargarArchivo_btn")
        self.FileLayout.addWidget(self.cargarArchivo_btn)
        self.input_archivo = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.input_archivo.setReadOnly(True)
        self.input_archivo.setObjectName("input_archivo")
        self.FileLayout.addWidget(self.input_archivo)
        self.graficar_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.graficar_btn.setObjectName("graficar_btn")
        self.FileLayout.addWidget(self.graficar_btn)
        self.puntoAClasificar = QtWidgets.QGroupBox(self.centralwidget)
        self.puntoAClasificar.setGeometry(QtCore.QRect(20, 160, 341, 71))
        self.puntoAClasificar.setObjectName("puntoAClasificar")
        self.label_x = QtWidgets.QLabel(self.puntoAClasificar)
        self.label_x.setGeometry(QtCore.QRect(20, 30, 16, 31))
        self.label_x.setObjectName("label_x")
        self.input_x = QtWidgets.QDoubleSpinBox(self.puntoAClasificar)
        self.input_x.setGeometry(QtCore.QRect(40, 30, 69, 31))
        self.input_x.setMinimum(-99.99)
        self.input_x.setSingleStep(0.1)
        self.input_x.setObjectName("input_x")
        self.label_y = QtWidgets.QLabel(self.puntoAClasificar)
        self.label_y.setGeometry(QtCore.QRect(130, 30, 16, 31))
        self.label_y.setObjectName("label_y")
        self.input_y = QtWidgets.QDoubleSpinBox(self.puntoAClasificar)
        self.input_y.setGeometry(QtCore.QRect(150, 30, 69, 31))
        self.input_y.setMinimum(-99.99)
        self.input_y.setSingleStep(0.1)
        self.input_y.setObjectName("input_y")
        self.clasificar_btn = QtWidgets.QPushButton(self.puntoAClasificar)
        self.clasificar_btn.setGeometry(QtCore.QRect(240, 30, 91, 31))
        self.clasificar_btn.setObjectName("clasificar_btn")
        self.cargaDatos = QtWidgets.QGroupBox(self.centralwidget)
        self.cargaDatos.setGeometry(QtCore.QRect(20, 60, 521, 91))
        self.cargaDatos.setObjectName("cargaDatos")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.cargaDatos)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 514, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.separatorLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.separatorLayout.setContentsMargins(0, 0, 0, 0)
        self.separatorLayout.setObjectName("separatorLayout")
        self.seleccionarSeparador = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.seleccionarSeparador.setObjectName("seleccionarSeparador")
        self.separatorLayout.addWidget(self.seleccionarSeparador)
        self.separador_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.separador_1.setMinimumSize(QtCore.QSize(65, 0))
        #self.separador_1.setChecked(False)
        self.separador_1.setObjectName("separador_1")
        self.separatorLayout.addWidget(self.separador_1)
        self.separador_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.separador_2.setObjectName("separador_2")
        self.separatorLayout.addWidget(self.separador_2)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.separatorLayout.addWidget(self.checkBox)
        self.clasificar_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.clasificar_btn_2.setGeometry(QtCore.QRect(380, 190, 161, 31))
        self.clasificar_btn_2.setObjectName("clasificar_btn_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 240, 231, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seleccionarK = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.seleccionarK.setProperty("checked", False)
        self.seleccionarK.setObjectName("seleccionarK")
        self.horizontalLayout.addWidget(self.seleccionarK)
        self.input_k = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.input_k.setMinimum(1)
        self.input_k.setMaximum(10)
        self.input_k.setObjectName("input_k")
        self.horizontalLayout.addWidget(self.input_k)
        self.rendimiento = QtWidgets.QGroupBox(self.centralwidget)
        self.rendimiento.setGeometry(QtCore.QRect(20, 300, 501, 161))
        self.rendimiento.setObjectName("rendimiento")
        self.probar_btn = QtWidgets.QPushButton(self.rendimiento)
        self.probar_btn.setGeometry(QtCore.QRect(160, 120, 181, 31))
        self.probar_btn.setObjectName("probar_btn")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.rendimiento)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 190, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.trainingLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.trainingLayout.setContentsMargins(0, 0, 0, 0)
        self.trainingLayout.setObjectName("trainingLayout")
        self.label_entrenamiento = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_entrenamiento.setObjectName("label_entrenamiento")
        self.trainingLayout.addWidget(self.label_entrenamiento)
        self.input_entrenamiento = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.input_entrenamiento.setMinimum(0)
        self.input_entrenamiento.setMaximum(100)
        self.input_entrenamiento.setProperty("value", 0)
        self.input_entrenamiento.setObjectName("input_entrenamiento")
        self.trainingLayout.addWidget(self.input_entrenamiento)
        self.label_porcentaje = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_porcentaje.setObjectName("label_porcentaje")
        self.trainingLayout.addWidget(self.label_porcentaje)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.rendimiento)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 70, 121, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.testLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.testLayout.setContentsMargins(0, 0, 0, 0)
        self.testLayout.setObjectName("testLayout")
        self.label_test = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_test.setObjectName("label_test")
        self.testLayout.addWidget(self.label_test)
        self.input_test = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.input_test.setReadOnly(True)
        self.input_test.setObjectName("input_test")
        self.testLayout.addWidget(self.input_test)
        self.label_porcentaje2 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_porcentaje2.setObjectName("label_porcentaje2")
        self.testLayout.addWidget(self.label_porcentaje2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.rendimiento)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 30, 221, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.grafico = QtWidgets.QGroupBox(self.centralwidget)
        self.grafico.setGeometry(QtCore.QRect(20, 470, 521, 251))
        self.grafico.setObjectName("grafico")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.grafico)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 501, 211))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.datos = QtWidgets.QGroupBox(self.centralwidget)
        self.datos.setGeometry(QtCore.QRect(550, 68, 411, 651))
        self.datos.setObjectName("datos")
        self.tableWidget = QtWidgets.QTableWidget(self.datos)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 391, 611))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 25))
        self.menubar.setObjectName("menubar")
        self.menuProyecto = QtWidgets.QMenu(self.menubar)
        self.menuProyecto.setObjectName("menuProyecto")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAyuda = QtWidgets.QAction(MainWindow)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionSobre_nosotros = QtWidgets.QAction(MainWindow)
        self.actionSobre_nosotros.setObjectName("actionSobre_nosotros")
        self.menuProyecto.addAction(self.actionNuevo)
        self.menuProyecto.addSeparator()
        self.menuProyecto.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionAyuda)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionSobre_nosotros)
        self.menubar.addAction(self.menuProyecto.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        self.cargarArchivo_btn.clicked.connect(MainWindow.browseSlot)
        self.graficar_btn.clicked.connect(MainWindow.graphSlot)
        self.probar_btn.clicked.connect(MainWindow.testSlot)
        self.clasificar_btn.clicked.connect(MainWindow.classifySlot)
        self.input_entrenamiento.valueChanged['int'].connect(MainWindow.updateTest)
        self.input_archivo.textChanged['QString'].connect(MainWindow.updateTable)
        self.input_entrenamiento.valueChanged['int'].connect(MainWindow.updateTrainingSet)
        self.input_entrenamiento.valueChanged['int'].connect(MainWindow.updateTable)
        self.clasificar_btn_2.clicked.connect(MainWindow.plotGrid)
        self.checkBox.clicked.connect(MainWindow.updateTable)
        self.separador_1.clicked.connect(MainWindow.updateTable)
        self.separador_2.clicked.connect(MainWindow.updateTable)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cargarArchivo_btn.setText(_translate("MainWindow", "Cargar Archivo"))
        self.graficar_btn.setText(_translate("MainWindow", "Graficar Dataset"))
        self.puntoAClasificar.setTitle(_translate("MainWindow", "Punto a Clasificar"))
        self.label_x.setText(_translate("MainWindow", "X"))
        self.label_y.setText(_translate("MainWindow", "Y"))
        self.clasificar_btn.setText(_translate("MainWindow", "Predecir"))
        self.cargaDatos.setTitle(_translate("MainWindow", "Carga de datos"))
        self.seleccionarSeparador.setText(_translate("MainWindow", "  Seleccionar Separador:"))
        self.separador_1.setText(_translate("MainWindow", ","))
        self.separador_2.setText(_translate("MainWindow", ";"))
        self.checkBox.setText(_translate("MainWindow", "El Dataset contiene cabecera?"))
        self.clasificar_btn_2.setText(_translate("MainWindow", "Graficar Clasificación"))
        self.seleccionarK.setText(_translate("MainWindow", "Seleccionar k:"))
        self.rendimiento.setTitle(_translate("MainWindow", "Probar Rendimiento"))
        self.probar_btn.setText(_translate("MainWindow", "Probar Rendimiento"))
        self.label_entrenamiento.setText(_translate("MainWindow", "Entrenamiento:"))
        self.label_porcentaje.setText(_translate("MainWindow", "%"))
        self.label_test.setText(_translate("MainWindow", "Test:"))
        self.label_porcentaje2.setText(_translate("MainWindow", "%"))
        self.radioButton.setText(_translate("MainWindow", "Mostrar todos"))
        self.radioButton_2.setText(_translate("MainWindow", "Mostrar óptimo y peor"))
        self.grafico.setTitle(_translate("MainWindow", "Información"))
        self.datos.setTitle(_translate("MainWindow", "Datos"))
        self.menuProyecto.setTitle(_translate("MainWindow", "Proyecto"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionAyuda.setText(_translate("MainWindow", "Ayuda"))
        self.actionSobre_nosotros.setText(_translate("MainWindow", "Sobre nosotros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

